-- Lab 6 - SQL/MM Spatial

-- Zad 1

-- A

select lpad('-',2*(level-1),'|-') || t.owner||'.'||t.type_name||' (FINAL:'||t.final||
       ', INSTANTIABLE:'||t.instantiable||', ATTRIBUTES:'||t.attributes||', METHODS:'||t.methods||')'
from all_types t
start with t.type_name = 'ST_GEOMETRY'
connect by prior t.type_name = t.supertype_name
       and prior t.owner = t.owner;

-- B

select distinct m.method_name
from all_type_methods m
where m.type_name like 'ST_POLYGON'
  and m.owner = 'MDSYS'
order by 1;

-- C.
CREATE TABLE MYST_MAJOR_CITIES (
    FIPS_CNTRY varchar2(2),
    CITY_NAME varchar2(40),
    STGEOM ST_POINT
);

-- D.
INSERT INTO MYST_MAJOR_CITIES SELECT FIPS_CNTRY, CITY_NAME, TREAT(ST_POINT.FROM_SDO_GEOM(GEOM) AS ST_POINT) STGEOM FROM ZTPD.MAJOR_CITIES;

SELECT * FROM MYST_MAJOR_CITIES;


-- Zad 2.

-- A.

INSERT INTO MYST_MAJOR_CITIES SELECT FIPS_CNTRY, CITY_NAME, TREAT(ST_POINT.FROM_SDO_GEOM(GEOM) AS ST_POINT) STGEOM FROM MAJOR_CITIES;
INSERT INTO MYST_MAJOR_CITIES VALUES('PL', 'Szczyrk', NEW ST_POINT(19.036107, 49.718655, NULL))

SELECT * FROM MYST_MAJOR_CITIES;

-- Zad 3.

-- A.

CREATE TABLE MYST_COUNTRY_BOUNDARIES (
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM ST_MULTIPOLYGON
);

-- B.

INSERT INTO MYST_COUNTRY_BOUNDARIES SELECT B.FIPS_CNTRY, B.CNTRY_NAME, ST_MULTIPOLYGON(B.GEOM) FROM COUNTRY_BOUNDARIES B;

-- C.
SELECT B.STGEOM.st_geometryType(), count(*) FROM MYST_COUNTRY_BOUNDARIES B GROUP BY B.STGEOM.st_geometryType();

-- D.

SELECT B.STGEOM.st_isSimple(), count(*) FROM MYST_COUNTRY_BOUNDARIES B GROUP BY B.STGEOM.st_isSimple();

-- Zad 4.

-- A.

DELETE FROM MYST_MAJOR_CITIES WHERE CITY_NAME = 'Szczyrk';

-- B.

SELECT C1.CNTRY_NAME C1_NAME, C2.CNTRY_NAME C2_NAME from MYST_COUNTRY_BOUNDARIES C1, MYST_COUNTRY_BOUNDARIES C2
where C1.STGEOM.ST_TOUCHES(C2.STGEOM) = 1 and C1.CNTRY_NAME = 'Czech Republic';

-- C.
SELECT DISTINCT B.CNTRY_NAME, R.NAME FROM MYST_COUNTRY_BOUNDARIES B, RIVERS R
WHERE B.CNTRY_NAME = 'Czech Republic' AND ST_LINESTRING(R.GEOM).ST_INTERSECTS(B.STGEOM) = 1;

-- D.

SELECT Treat(C1.STGEOM.ST_UNION(C2.STGEOM) as ST_POLYGON).ST_AREA() CZECHOSLOWACJA
FROM MYST_COUNTRY_BOUNDARIES C1, MYST_COUNTRY_BOUNDARIES C2 WHERE C1.CNTRY_NAME = 'Czech Republic' AND C2.CNTRY_NAME = 'Slovakia';

-- E.

select C1.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(W.GEOM)) WEGRY_BEZ, C1.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(W.GEOM)).st_geometryType() Typ
from MYST_COUNTRY_BOUNDARIES C1, WATER_BODIES W where C1.CNTRY_NAME = 'Hungary' and W.name = 'Balaton';

-- Zad 5.

-- A.

SELECT B.CNTRY_NAME A_NAME, count(*) FROM MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE' AND B.CNTRY_NAME = 'Poland'
GROUP BY B.CNTRY_NAME;

-- B.
INSERT INTO USER_SDO_GEOM_METADATA SELECT 'MYST_MAJOR_CITIES', 'STGEOM', T.DIMINFO, T.SRID FROM USER_SDO_GEOM_METADATA T
WHERE T.TABLE_NAME = 'MAJOR_CITIES';

-- C.
CREATE INDEX MYST_MAJOR_CITIES_IDX ON MYST_MAJOR_CITIES(STGEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- D.
EXPLAIN PLAN FOR
SELECT B.CNTRY_NAME A_NAME, count(*) FROM MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE' AND B.CNTRY_NAME = 'Poland'
GROUP BY B.CNTRY_NAME;