-- Lab 7 - Linear Referencing System

-- Zad 1

-- A.

CREATE TABLE A6_LRS (
    GEOM SDO_GEOMETRY
);

-- B.

INSERT INTO A6_LRS SELECT SDO_LRS.CONVERT_TO_LRS_GEOM(SR.GEOM, 0, 276.681)
FROM STREETS_AND_RAILROADS SR, MYST_MAJOR_CITIES M
WHERE SDO_WITHIN_DISTANCE(SR.GEOM, M.STGEOM, 'distance=10 unit=km') = 'TRUE' AND M.CITY_NAME = 'Koszalin';

-- C.

SELECT UNIQUE SDO_GEOM.SDO_LENGTH(a.GEOM, 1, 'unit=km') DISTANCE, ST_LINESTRING(a.GEOM).ST_NUMPOINTS() ST_NUMPOINTS FROM A6_LRS a;

-- E.
INSERT INTO USER_SDO_GEOM_METADATA VALUES ('A6_LRS','GEOM',
    MDSYS.SDO_DIM_ARRAY(
            MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
            MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
            MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1) ),
    8307);

-- F.
CREATE INDEX A6_LRS_INDEX ON A6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- Zad 2.

-- A.

SELECT UNIQUE SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500 FROM A6_LRS;

-- B.

SELECT UNIQUE SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT from A6_LRS;

-- C.

SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) KM150 FROM A6_LRS;

-- D.

SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPED FROM A6_LRS;

-- E.

select SDO_LRS.PROJECT_PT(A6.GEOM, C.GEOM) WJAZD_NA_A6
from A6_LRS A6, MAJOR_CITIES C where C.CITY_NAME = 'Slupsk';

-- F.

select SDO_GEOM.SDO_LENGTH((select SDO_LRS.OFFSET_GEOM_SEGMENT(A6.GEOM, M.DIMINFO, 50, 200, 50, 'unit=m arc_tolerance=1')
                from A6_LRS A6, USER_SDO_GEOM_METADATA M where M.TABLE_NAME = 'A6_LRS' and M.COLUMN_NAME = 'GEOM'), 1,'unit=km') koszt from dual;